# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn run build
      - run: mkdir $CIRCLE_ARTIFACTS/es
      - run: mkdir $CIRCLE_ARTIFACTS/lib
      - run: cp es/*.* $CIRCLE_ARTIFACTS/es
      - run: cp lib/*.* $CIRCLE_ARTIFACTS/lib


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: echo "test"